spring.application.name=insurance-fraud-backend
server.port = 8081
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/insurance_db
spring.datasource.username=insurance_user
spring.datasource.password=Vivek@2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vivek.narawade@aissmsioit.org
spring.mail.password=mqkiqxvimsvcgoob
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.apache.commons.mail=DEBUG



#SECURITY CONFIG
#spring.security.user.name =Vivek
#spring.security.user.password=123


jwt.secret=4F8xK9mP2QaL7vBn3TzW6HsY1DcR5EfU8JiN0KoLpXc
jwt.access.expiration=15m
jwt.refresh.expiration=7d
