spring.config.import=optional:file:.env[.properties]

spring.application.name=insurance-fraud-backend
server.port = ${SERVER_PORT:8081}
server.address=0.0.0.0

# DATABASE (Defaults to Localhost MySQL)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/insurance_fraud_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# AI FRAUD MICROSERVICE URL (Defaults to Localhost Python FastAPI)
ai.fraud.service.url=${AI_SERVICE_URL:http://localhost:8000/api/v1/analyze-claim}

# MAIL CONFIG
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USER:test@example.com}
spring.mail.password=${MAIL_PASSWORD:password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false

# JWT
jwt.secret=${JWT_SECRET:4F8xK9mP2QaL7vBn3TzW6HsY1DcR5EfU8JiN0KoLpXc}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION:15m}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:7d}

# FILE UPLOAD CONFIG
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Local development folder
file.upload-dir=./images

# STORAGE PROVIDER (local or cloudinary)
storage.provider=${STORAGE_PROVIDER:local}


